title: Image Analysis Training
email: image-analysis-support@embl.de
description: > # this means to ignore newlines until "baseurl:"
  A collection of material for teaching image analysis.
  Includes concept maps, exercises, example data
baseurl: "/image-analysis-training-resources" # the subpath of your site, e.g. /blog
url: "https://grp-bio-it.embl-community.io/" # the base hostname & protocol for your site
contributing: CONTRIBUTING

# Build settings
markdown: CommonMarkGhPages
commonmark:
  options: ["SMART"]
highlighter: rouge
exclude: ["README.md", "TEACHING.md"]

# options are: "NONE", "ImageJ GUI", "ImageJ Macro", "Jython", "MATLAB"
default-platform: "NONE"
